pinaxcon/attendees/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static


from . import views

urlpatterns = [
    url(r"^create/$", views.attendee_create, name="attendee_create"),
    url(r"^edit/(?:(?P<pk>\d+)/)?$", views.attendee_edit, name="attendee_edit"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pinaxcon/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin

import symposion.views
from pinaxcon import views
from pinaxcon.attendees import views as attendee_views

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^agenda/$", TemplateView.as_view(template_name="agenda.html"), name="agenda"),
    url(r"^becas/$", views.becas, name="becas"),
    url(r"^schedule.json$", views.schedule_json, name="schedule_json"),
    url(r"^diversidad/$", TemplateView.as_view(template_name="declaracion_diversidad.html"), name="diversidad"),
    url(r"^codigo-conducta/$", TemplateView.as_view(template_name="codigo_conducta.html"), name="codigo-de-conducta"),
    url(r"^forma-parte/$", TemplateView.as_view(template_name="forma_parte.html"), name="forma-parte"),
    url(r"^alojamiento/$", TemplateView.as_view(template_name="alojamiento.html"), name="alojamiento"),
    url(r"^organizadores/$", TemplateView.as_view(template_name="organizadores.html"), name="organizadores"),
    url(r"^sponsors/$", TemplateView.as_view(template_name="sponsors.html"), name="sponsors"),
    url(r"^admin/", include(admin.site.urls)),

    url(r"^account/", include("account.urls")),

    url(r"^dashboard/", symposion.views.dashboard, name="dashboard"),

    url(r"^speaker/", include("symposion.speakers.urls")),
    url(r"^proposals/", include("symposion.proposals.urls")),
    url(r"^sponsors/", include("symposion.sponsorship.urls")),
    url(r"^reviews/", include("symposion.reviews.urls")),
    url(r"^schedule/", include("symposion.schedule.urls")),
    url(r"^attendee/", include("pinaxcon.attendees.urls")),
    url(r"^teams/", include("symposion.teams.urls")),

    url(r"^boxes/", include("pinax.boxes.urls")),
    url(r'^captcha/', include('captcha.urls')),
    url(r"^", include("pinax.pages.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pinaxcon/attendees/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime

from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User


@python_2_unicode_compatible
class Attendee(models.Model):
    user = models.OneToOneField(User, related_name="attendee", verbose_name=_("User"))
    full_name = models.CharField(verbose_name="Nombre completo o nick", max_length=100,
                            help_text=(u"Como te gustaría que se imprima en tu"
                                        " gafete.(si querés puede ser un nick)"))
    annotation = models.TextField(verbose_name="Observaciones",
                                  help_text=("Si tenés alguna necesidad "
                                  "particular que necesites que contemplemos "
                                  "para el evento contanos y haremos lo posible "
                                  "por ayudarte. "
                                  "Te recomendamos reservar tu vianda para los "
                                  "días sábado y domingo, ya que cerca del "
                                  "complejo las ofertas gastronómicas son "
                                  "reducidas Podrás elegir el tipo de vianda de "
                                  "acuerdo a tus necesidades. Encontrarás el "
                                  "link para hacerlo al confirmar la "
                                  "registración."),
                                  blank=True, null=True)
    registration_date = models.DateTimeField(auto_now_add=True,
        editable=False)
    cv = models.FileField(upload_to="attendees_cvs", blank=True,
            verbose_name="Curriculum vitae")
    show_to_sponsor = models.BooleanField(verbose_name="Compartir mis datos "
                                          "personales", help_text=("Acepto que mis datos "
        "personales se compartan con los sponsors"))

    class Meta:
        ordering = ['full_name']
        verbose_name = "Asistente"
        verbose_name_plural = "Asistentes"

    def __str__(self):
        if self.user:
            return self.full_name
        else:
            return "?"

pinaxcon/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime

from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.postgres.fields import ArrayField

from symposion.markdown_parser import parse


@python_2_unicode_compatible
class Attendee(models.Model):
    NONE = 'NON'
    VEGETARIANO = 'VEG'
    VEGANO = 'VGN'
    BAJO_SODIO = 'SOD'
    CELIACO = 'CEL'
    OTROS = 'CEL'
    FOOD_PREFERENCE_CHOICES = (
        (NONE, 'No tengo preferencia/necesidad'),
        (BAJO_SODIO, 'Bajo en sodio'),
        (VEGANO, 'Vegano'),
        (VEGETARIANO, 'Vegetariano'),
        (CELIACO, 'Celiaco'),
        (OTROS, 'Otros'),)


    user = models.OneToOneField(User, null=True, related_name="attendee", verbose_name=_("User"))
    full_name = models.CharField(verbose_name="Nombre completo o nick", max_length=100,
                            help_text=(u"Como te gustaría que se imprima en tu"
                                        " gafete.(si querés puede ser un nick)"))
    annotation = models.TextField(verbose_name="Observaciones",
                                  help_text=("Si tenés alguna necesidad"
                                      "especial que necesites que"
                                      "contemplemos,"
                                      "por favor completa este campo"))
    food_preference = ArrayField(
        models.CharField(verbose_name="Preferencia o necesidad alimenticia",
                                  help_text=("Vas a poder comprar y reservar"
                                      "tus viandas por internet previo al"
                                      "evento(preferentemente), o en el lugar"
                                      "completando este campo nos aseguramos"
                                      "de poder cubrir las necesidades de todos"),
			choices=FOOD_PREFERENCE_CHOICES, max_length=3,
                        blank=True, default=NONE),)

    registration_date = models.DateTimeField(auto_now_add=True,
        editable=False)
    cv = models.FileField(upload_to="attendees_cvs", blank=True,
            verbose_name="Curriculum vitae")
    show_to_sponsor = models.BooleanField( help_text=("Acepto que mis datos"
        "personales se compartan con los sponsors"))

    class Meta:
        ordering = ['full_name']
        verbose_name = "Asistente"
        verbose_name_plural = "Asistentes"

    def __str__(self):
        if self.user:
            return self.full_name
        else:
            return "?"

pinaxcon/proposals/models.py
# -*- coding: utf-8 -*-
from django.db import models

from symposion.proposals.models import ProposalBase


class Proposal(ProposalBase):

    AUDIENCE_LEVEL_NOVICE = 1
    AUDIENCE_LEVEL_EXPERIENCED = 2
    AUDIENCE_LEVEL_INTERMEDIATE = 3

    AUDIENCE_LEVELS = [
        (AUDIENCE_LEVEL_NOVICE, "Principiante"),
        (AUDIENCE_LEVEL_INTERMEDIATE, "Intermedia"),
        (AUDIENCE_LEVEL_EXPERIENCED, "Avanzada"),
    ]

    audience_level = models.IntegerField(choices=AUDIENCE_LEVELS)

    recording_release = models.BooleanField(
        default=True,
        help_text="Al enviar tu propuesta, le estás dando permiso a los organizadores de la conferencia para grabar, editar y transmitir audio y/o video de tu presentación. Si no estas de acuerdo con esto, no chequees este recuadro."
    )

    class Meta:
        abstract = True


class TalkProposal(Proposal):

    class Meta:
        verbose_name = "Propuesta de charla/taller"
        verbose_name_plural = "Propuestas de charlas/talleres"

pinaxcon/attendees/forms.py
# -*- coding: utf-8 -*-
from django import forms
from captcha.fields import CaptchaField

from .models import Attendee


class AttendeeForm(forms.ModelForm):

    class Meta:
        model = Attendee
        fields = [
            "full_name",
            "annotation",
            "cv",
            "show_to_sponsor",
        ]

pinaxcon/forms.py
# -*- coding: utf-8 -*-
from django import forms
from captcha.fields import CaptchaField

class BecasForm(forms.Form):
    nombre_completo = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    que_necesitas = forms.CharField(
        required=True,
        widget=forms.Textarea,
        label=u"¿Qué necesitás?"
    )
    ingresa_el_texto = CaptchaField()

pinaxcon/proposals/forms.py
# -*- coding: utf-8 -*-

from django import forms

from .models import TalkProposal


class ProposalForm(forms.ModelForm):

    def clean_description(self):
        value = self.cleaned_data["description"]
        if len(value) > 400:
            raise forms.ValidationError(
                u"La descripción debe ser menor a 400 caracteres"
            )
        return value


class TalkProposalForm(ProposalForm):

    class Meta:
        model = TalkProposal
        fields = [
            "title",
            "audience_level",
            "description",
            "abstract",
            "additional_notes",
            "recording_release",
        ]

pinaxcon/attendees/views.py
# -*- coding: utf-8 -*-
from account.decorators import login_required
from django.shortcuts import render, redirect
from django.template import loader
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import EmailMessage
from django.contrib import messages
from django.template import Context

from .forms import AttendeeForm
from .models import Attendee

@login_required
def attendee_create(request):
    user = request.user

    attendee = getattr(request.user, "attendee", None)

    if attendee is not None:
        messages.error(request, u"Ya te encontrás registrado para la PyconAR.")
        return redirect("dashboard")

    if request.method == "POST":
        form = AttendeeForm(request.POST, request.FILES)

        if form.is_valid():
            attendee = form.save(commit=False)
            attendee.user = user
            attendee.save()
            # Email the profile with the
            # contact information
            template = loader.get_template('inscripcion.txt')
            context = Context({
                'contact_name': attendee.full_name,
            })
            content = template.render(context)

            email = EmailMessage(
                "Inscripción PyconAR 2016 - Bahía Blanca",
                content,
                "no-reply@python.org.ar",
               [user.email]
            )
            email.send()

            messages.success(request, u"¡Te registraste exitosamente a la pyconAR te esperamos!.")
            return redirect("dashboard")
    else:
        form = AttendeeForm(initial={"name": request.user.get_full_name()})
    return render(request, "attendee/attendee_create.html", {
        "attendee_form": form,
    })


@login_required
def attendee_edit(request, pk=None):
    if pk is None:
        try:
            attendee = request.user.attendee
        except Attendee.DoesNotExist:
            return redirect("attendee_create")
    else:
        if request.user.is_staff:
            attendee = get_object_or_404(Attendee, pk=pk)
        else:
            raise Http404()

    if request.method == "POST":
        form = AttendeeForm(request.POST, request.FILES, instance=attendee)
        if form.is_valid():
            form.save()
            messages.success(request, "Perfil de asistente actualizado")
            return redirect("dashboard")
    else:
        form = AttendeeForm(instance=attendee)

    return render(request, "attendee/attendee_edit.html", {
        "attendee_form": form,
    })

pinaxcon/views.py
# -*- coding: utf-8 -*-
import json

from django.contrib import messages
from django.contrib.sites.models import Site
from django.core.mail import EmailMessage
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render
from django.template import Context, loader
from symposion.schedule.models import Slot

from .forms import BecasForm

def becas(request):
    form_class = BecasForm

    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get(
                'nombre_completo')
            contact_email = request.POST.get(
                'email')
            form_content = request.POST.get('que_necesitas')

            # Email the profile with the
            # contact information
            template = loader.get_template('becas_email.txt')
            context = Context({
                'contact_name': contact_name,
                'contact_email': contact_email,
                'form_content': form_content,
            })
            content = template.render(context)

            email = EmailMessage(
                "[BECAS]Nueva beca requerida",
                content,
                "no-reply@python.org.ar",
                ['pyconar@listas.bitson.com.ar'],
                headers = {'Reply-To': contact_email }
            )
            email.send()
            messages.add_message(request, messages.INFO, u"""¡Gracias por tu solicitud!, nos pondremos en contacto a la brevedad para
 informarte de los pasos a seguir""")

            return redirect('becas')
        else:
            messages.add_message(request, messages.ERROR, u"""Por favor completa los campos correctamente""")

    return render(request, 'becas.html', {
        'form': form_class,
    })



def schedule_json(request):
    slots = Slot.objects.filter(
        day__schedule__published=True,
        day__schedule__hidden=False
    ).order_by("start")

    protocol = request.META.get('HTTP_X_FORWARDED_PROTO', 'http')
    data = []
    for slot in slots:
        slot_data = {
            "room": ", ".join(room["name"] for room in slot.rooms.values()),
            "rooms": [room["name"] for room in slot.rooms.values()],
            "start": slot.start_datetime.isoformat(),
            "end": slot.end_datetime.isoformat(),
            "duration": slot.length_in_minutes,
            "kind": slot.kind.label,
            "section": slot.day.schedule.section.slug,
            "conf_key": slot.pk,
            # TODO: models should be changed.
            # these are model features from other conferences that have forked symposion
            # these have been used almost everywhere and are good candidates for
            # base proposals
            #"license": "CC BY",
            "tags": "",
            #"released": True,
            "contact": [],


        }
        if hasattr(slot.content, "proposal"):
            slot_data.update({
                "name": slot.content.title,
                "authors": [s.name for s in slot.content.speakers()],
                "contact": [
                    s.email for s in slot.content.speakers()
                ] if request.user.is_staff else ["redacted"],
                "abstract": slot.content.abstract,
                "description": slot.content.description,
                "conf_url": "%s://%s%s" % (
                    protocol,
                    Site.objects.get_current().domain,
                    reverse("schedule_presentation_detail", args=[slot.content.pk])
                ),
                "cancelled": slot.content.cancelled,
            })
        else:
            slot_data.update({
                "name": slot.content_override.raw if slot.content_override else "Slot",
            })
        data.append(slot_data)

    return HttpResponse(
        json.dumps({"schedule": data}),
        content_type="application/json"
    )

pinaxcon/templates/pinax/submissions/_pending_proposal_row.html
{% load i18n %}

<tr>
    <td>
        <a href="{% url "proposal_detail" proposal.pk %}">{{ proposal.title }}</a>
    </td>

    <td>{{ proposal.kind.name }}</td>

    <td>
        {% if proposal.cancelled %}
            <span class="label label-danger">{% trans 'Cancelled' %}</span>
        {% else %}
            {% if request.user == proposal.speaker.user %}
                {% if proposal.result.status == "accepted" %}
                    <span class="label label-success">{% trans 'Accepted' %}</span>
                {% else %}
                    <span class="label label-default">{% trans 'Submitted' %}</span>
                {% endif %}
            {% else %}
                <span class="label label-default">{% trans 'Invited' %}</span>
            {% endif %}
        {% endif %}
    </td>

    <td>
        {% if not proposal.cancelled %}
            <div class="btn-group">
                <a class="btn btn-xs dropdown-toggle" data-toggle="dropdown" href="#">
                {% trans 'Choose Response' %}
                <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="{% url "proposal_pending_join" proposal.id %}">
			{% trans 'Accept invitation' %}</a></li>
                    <li><a href="{% url "proposal_pending_decline" proposal.id
		    %}">{% trans 'Decline invitation' %}</a></li>
                </ul>
            </div>
        {% endif %}
    </td>
</tr>

pinaxcon/templates/pinax/submissions/_proposal_row.html
<tr>
    <td>
        <a href="{% url "proposal_detail" proposal.pk %}">{{ proposal.title }}</a>
    </td>

    <td>{{ proposal.kind.name }}</td>

    <td>
        {% if proposal.cancelled %}
            <span class="label label-danger">Cancelled</span>
        {% else %}
            {% if request.user == proposal.speaker.user %}
                {% if proposal.result.status == "accepted" %}
                    <span class="label label-success">Accepted</span>
                {% else %}
                    <span class="label label-default">Submitted</span>
                {% endif %}
            {% else %}
                <span class="label label-default">Associated</span>
            {% endif %}
        {% endif %}
    </td>

    <td>
        {% if not proposal.cancelled %}
            {% if request.user == proposal.speaker.user and proposal.can_edit %}
                <a href="{% url "proposal_edit" proposal.pk %}" class="btn btn-xs"><i class="fa fa-pencil"></i> Edit</a>
                <a href="{% url "proposal_speaker_manage" proposal.id %}" class="btn btn-xs"><i class="fa fa-user"></i> Manage Additional Speakers</a>
            {% endif %}
        {% endif %}
    </td>
</tr>

pinaxcon/templates/pinax/submissions/_result_notification_prepare_help.html
    <b>Body</b> may include the following variables which will be substituted in the email with a value
    specific to each proposal:
<ul>
    <li><code>{% templatetag openvariable %} proposal.title {% templatetag closevariable %}</code> e.g. {{ proposals.0.title }}
    <li><code>{% templatetag openvariable %} proposal.kind {% templatetag closevariable %}</code> e.g. {{ proposals.0.kind }}
    <li><code>{% templatetag openvariable %} proposal.speaker {% templatetag closevariable %}</code> e.g. {{ proposals.0.speaker }}
</ul>

pinaxcon/templates/pinax/submissions/_review_table.html
{% load i18n %}

<table class="table table-striped table-bordered table-reviews">
    <thead>
        <th>#</th>
        <th>{% trans "Speaker / Title" %}</th>
        <th>{% trans "Category" %}</th>
        <th><i class="fa fa-comment-alt"></i></th>
        <th>{% trans "+1" %}</th>
        <th>{% trans "+0" %}</th>
        <th>{% trans "-0" %}</th>
        <th>{% trans "-1" %}</th>
        <th><a href="#" class="tip" title="{% trans "Your Rating" %}"><i class="fa fa-user"></i></a></th>
    </thead>

    <tbody>
        {% for proposal in proposals %}
            <tr class="{{ proposal.user_vote_css }}">
                <td>{{ proposal.number }}</td>
                <td>
                    <a href="{% url "review_detail" proposal.pk %}">
                        <small><strong>{{ proposal.speaker }}</strong></small>
                        <br />
                        {{ proposal.title }}
                    </a>
                </td>
                <td>{{ proposal.track }}</td>
                <td>{{ proposal.comment_count }}</td>
                <td>{{ proposal.plus_one }}</td>
                <td>{{ proposal.plus_zero }}</td>
                <td>{{ proposal.minus_zero }}</td>
                <td>{{ proposal.minus_one }}</td>
                <td>{{ proposal.user_vote|default:"" }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>

pinaxcon/templates/pinax/submissions/base.html
{% extends "site_base.html" %}

{% load i18n %}
{% load sitetree %}

{% block extra_style %}
    <style type="text/css">
        div.dataTables_length label {
            float: left;
            text-align: left;
        }

        div.dataTables_length select {
            width: 75px;
        }

        div.dataTables_filter label {
            float: right;
        }

        div.dataTables_info {
            padding-top: 8px;
        }

        div.dataTables_paginate {
            float: right;
            margin: 0;
        }

        table.table {
            clear: both;
            margin-bottom: 6px !important;
            background-color: white;
        }

        table.table thead .sorting,
        table.table thead .sorting_asc,
        table.table thead .sorting_desc,
        table.table thead .sorting_asc_disabled,
        table.table thead .sorting_desc_disabled {
            cursor: pointer;
            *cursor: hand;
        }

        table.dataTable th:active {
            outline: none;
        }
    </style>
{% endblock %}

{% block body_class %}reviews{% endblock %}

{% block body_outer %}
    <div class="row">
        <div class="col-md-2">
            {% block sidebar %}
                <ul class="nav nav-list well">
                    {% for section in review_sections %}
                        <li class="nav-header">
                            {{ section }}
                        </li>
                        <li>
                            <a href="{% url "review_section" section.section.slug %}">
                                {% trans "All Reviews" %}
                            </a>
                        </li>
                        {% comment %}
                        <li>
                            <a href="{% url "review_section_assignments" section.section.slug %}">
                                {% trans "Your Assignments" %}
                            </a>
                        </li>
                        {% endcomment %}
                        <li>
                            <a href="{% url "review_status" section.section.slug %}">
                                {% trans "Voting Status" %}
                            </a>
                        </li>
                        {% if request.user.is_staff %}
                            <li>
                                <a href="{% url "result_notification" section.section.slug 'accepted' %}">Result Notification</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            {% endblock %}
        </div>
        <div class="col-md-10">
            {% block body %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

{% block extra_script %}
    <script src="{{ STATIC_URL }}datatables/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}tabletools/js/TableTools.min.js" type="text/javascript"></script>
    <script src="{{ STATIC_URL }}datatables/js/dataTables.bootstrap.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function() {
            $(".tip").tooltip();
            $("table.table-reviews").dataTable({
                "sDom": "<'row'<'col-md-3'l><'col-md-3'T><'col-md-4'f>r>t<'row'<'col-md-3'i><'col-md-5'p>>",
                "sPaginationType": "bootstrap",
                "bStateSave": true,
                "oTableTools": {
                    "aButtons": [
                        "copy",
                        "csv",
                        "print"
                    ],
                    "sSwfPath": "{{ STATIC_URL }}tabletools/swf/copy_csv_xls.swf"
                }
            });
        });
    </script>
{% endblock %}

pinaxcon/templates/pinax/submissions/proposal_cancel.html
{% extends "symposion/proposals/base.html" %}

{% load i18n %}

{% block head_title %}{% trans 'Cancel Proposal' %}{% endblock %}

{% block body %}
    <h1>Cancel: {{ proposal.title }}</h1>

    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Are you sure you want to cancel <b>{{ proposal.title }}</b>?</p>
        <input class="btn btn-danger" type="submit" value="I am sure" />
        <a class="btn btn-default" href="{% url "proposal_detail" proposal.pk %}">{% trans 'No, keep it for now' %}</a>
    </form>
{% endblock %}

pinaxcon/templates/pinax/submissions/proposal_edit.html
{% extends "symposion/proposals/base.html" %}

{% load bootstrap %}

{% block head_title %}Editing {{ proposal.title }}{% endblock %}

{% block body %}
    <h1>Edit: {{ proposal.title }}</h1>

    <p><a href="{% url "proposal_speaker_manage" proposal.pk %}">Manage speakers</a></p>

    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>
            {{ form|bootstrap }}
        </fieldset>
        <div class="form-actions">
            <input class="btn btn-primary" type="submit" value="Save" />
            <a class="btn btn-default" href="{% url "proposal_detail" proposal.pk %}">Cancel</a>
        </div>
    </form>
{% endblock %}

pinaxcon/templates/pinax/submissions/proposal_leave.html
{% extends "symposion/proposals/base.html" %}

{% block body %}
    <h3>Leaving {{ proposal.title }}</h3>

    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <p>Are you sure you wish to leave as a speaker on <b>{{ proposal.title }}</b>?</p>
        <input type="submit" class="btn btn-primary" value="I am sure" />
    </form>
{% endblock %}

pinaxcon/templates/pinax/submissions/review_admin.html
{% extends "symposion/reviews/base.html" %}

{% block body %}
    <h1>Reviewers</h1>

    <table class="table table-striped">
        <tr>
            <th>
                Reviewer
            </th>
            <th>
                Proposals<br/>Reviewed
            </td>
            <th>
                Comments
            </th>
            <th>
                +1
            </th>
            <th>
                +0
            </th>
            <th>
                &minus;0
            </th>
            <th>
                &minus;1
            </th>
        </tr>
        {% for reviewer in reviewers %}
        <tr>
            <td>
                <a href="{% url "review_list_user" section_slug reviewer.pk %}">{{ reviewer.get_full_name }}</a>
            </td>
            <td>
                {{ reviewer.total_votes }}
            </td>
            <td>
                {{ reviewer.comment_count }}
            </td>
            <td>
                {{ reviewer.plus_one }}
            </td>
            <td>
                {{ reviewer.plus_zero }}
            </td>
            <td>
                {{ reviewer.minus_zero }}
            </td>
            <td>
                {{ reviewer.minus_one }}
            </td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}

pinaxcon/templates/pinax/submissions/review_assignment.html
{% extends "symposion/reviews/base.html" %}

{% block body %}
    <h1>Review Assignments</h1>

    {% if assignments %}
        <table>
            <tr>
                <th>Proposal</th>
                <th>Opted out</th>
                <th>Opt out</th>
            </tr>
            {% for assignment in assignments %}
                <tr>
                    <td>
                        <a href="{% url review_detail assignment.proposal.pk %}">
                            {{ assignment.proposal.title }}
                        </a>
                    </td>
                    <td>
                        <form method="post" action="{% url "review_assignment_opt_out" assignment.pk %}">
                            {% csrf_token %}
                            <input type="submit" value="Opt-out" />
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>You do not have any assignments.</p>
    {% endif %}
{% endblock %}

pinaxcon/templates/pinax/submissions/review_comment.html
{{ proposal }}: proposal obj
{{ form }}: comment form obj

pinaxcon/templates/pinax/submissions/review_review.html
{% extends "site_base.html" %}

{% load bootstrap %}

{% block body_class %}review{% endblock %}

{% block body %}
    <h1>Proposal Review</h1>

    <div class="proposal">
        <h2>{{ proposal.title }}</h2>

        <p>
            {% if proposal.cancelled %}
                Cancelled
            {% endif %}
        </p>

        <div>
            {{ proposal.description }}
        </div>

        <p><b>Type</b>: {{ proposal.get_session_type_display }}</p>

        <h3>Abstract</h3>
        <div class="abstract">
            {{ proposal.abstract_html|safe }}
        </div>

        <p><b>Audience level</b>: {{ proposal.get_audience_level_display }}</p>

        <p><b>Submitting speaker</b>: {{ proposal.speaker }}</p> {# @@@ bio? #}

        {% if proposal.additional_speakers.all %}
            <p><b>Additional speakers</b>:</p>
            <ul>
            {% for speaker in proposal.additional_speakers.all %}
                {% if speaker.user %}
                    <li><b>{{ speaker.name }}</b> &mdash; {{ speaker.email }}</li>
                {% else %}
                    <li>{{ speaker.email }} &mdash; pending invitation</li>
                {% endif %}
            {% endfor %}
            </ul>
        {% endif %}

        <h3>Additional Notes (private from submitter)</h3>
        <div class="additional_notes">
            {{ proposal.additional_notes }}
        </div>
    </div>

    <h2>Review</h2>

    <form method="POST" action="{% url "review_review" proposal.pk %}" class="form">
        {% csrf_token %}
        <fieldset class="inlineLabels">
            {{ review_form|bootstrap }}
            <div class="form_block">
                <input type="submit" value="Submit" />
            </div>
        </fieldset>
    </form>

    <h2>Comment</h2>

    <form method="POST" action="{% url "review_comment" proposal.pk %}" class="form">
        {% csrf_token %}
        <fieldset>
            {{ comment_form|bootstrap }}
            <div class="form_block">
                <input type="submit" value="Submit" />
            </div>
        </fieldset>
    </form>

{% endblock %}